### PR TITLE
[Snyk + GH Actions] Update requirements

### PR DESCRIPTION
**Pull request by Jin-Sun-tts**
Update requirements
- Updated `requirements.in` + `requirements.txt`
- Auto-generated by [snyk.yml][1]

[1]: https://github.com/gsa/inventory-app/.github/workflows/snyk.yml

### CODE REVIEW

**Comment by btylerburton** [comment]
does this build? i thought we couldn't upgrade werkzeug.

**Comment by rshewitt** [comment]
> does this build? i thought we couldn't upgrade werkzeug.

@btylerburton i'm not seeing workzeug being upgraded in this commit

**Comment by btylerburton** [comment]
I see she force-pushed. 
Maybe the older commit had it? Or I got my wires crossed. So long as it builds I'm sure it's ok.

**Review by rshewitt — APPROVED** [review]

**Comment by FuhuXia** [comment]
The change made to requirements.in.txt is absurd.

**Comment by FuhuXia** [comment]
> I see she force-pushed. Maybe the older commit had it? Or I got my wires crossed. So long as it builds I'm sure it's ok.

That is a bot, pronoun it, not she. :laughing:

**Pull request merged**
