### PR TITLE
[Snyk + GH Actions] Update requirements

### PR DESCRIPTION
**Pull request by Jin-Sun-tts**
Update requirements
- Updated `requirements.in` + `requirements.txt`
- Auto-generated by [snyk.yml][1]

[1]: https://github.com/gsa/inventory-app/.github/workflows/snyk.yml

### CODE REVIEW

**Comment by btylerburton** [comment]
In this PR: 
- Added `update-dependencies` command to Makefile
- Sorted make commands A-Z
- Fixed lint

**Comment by FuhuXia** [comment]
We have `make requirements`, why a new `make update-dependencies`?

**Comment by btylerburton** [comment]
@FuhuXia i didn't see that! will remove.

**Comment by btylerburton** [comment]
@FuhuXia updated

**Review by jbrown-xentity — APPROVED** [review]

**Pull request merged**
