### PR TITLE
Fix ckanext-datajson

### PR DESCRIPTION
**Pull request by adborden**
requirements.txt was pointing to the wrong branch.

### CODE REVIEW

**Comment by adborden** [comment]
Part of https://github.com/GSA/datagov-deploy/issues/1047

**Comment by adborden** [comment]
You're seeing buttons missing? Can you post a screenshot?

**Comment by adborden** [comment]
@jbrown-xentity you're right! I thought this was the same commit that is on production, but it looks like that's not the case and this version has some significant changes for CKAN 2.8. I'll revert to the commit that is on production while we debug what's going on with ckanext-datajson.

Local devleopment:
Screenshot from 2020-01-10 12-13-18


Production:
Screenshot from 2020-01-10 12-16-06

**Comment by jbrown-xentity** [comment]
Glad we got some clarification on that. Let me know if you need another review or any other checks. I know when I was clicking around while testing none of the buttons actually worked on dev, so maybe some checks should be created to validate the expected functionality inside the tests.

**Comment by adborden** [comment]
@jbrown-xentity this is ready for another review. I opened this https://github.com/GSA/ckanext-datajson/issues/52

Realizing that Inventory and Catalog are running two different forks of this extension :(

**Comment by adborden** [comment]
Testing on sandbox.. if we're reverting, I'm not sure why this PR is even necessary.

**Comment by adborden** [comment]
Yeah, it seems this fix isn't necessary.

**Pull request closed without merging**
