### PR TITLE
Solr 8 Integration

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to https://github.com/GSA/datagov-deploy/issues/3523 and https://github.com/GSA/datagov-deploy/issues/3697

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
This is a problem for catalog too, but the way that okfn [checks for solr being ready](https://github.com/okfn/docker-ckan/blob/master/ckan-base/2.9/setup/prerun.py#L66-L85) no longer works with Solr 8,
Solr 6 (works 😀):
```
>>> a = urlopen("http://localhost:8983/solr/ckan/select/?&wt=json")
>>> eval(a.read())
{'responseHeader': {'status': 0, 'QTime': 1, 'params': {'wt': 'json'}}, 'response': {'numFound': 0, 'start': 0, 'docs': []}}
```
Solr 8 (no work 😢):
```
>>> from urllib.request import urlopen
>>> a = urlopen("http://localhost:8983/solr/ckan/select/?&wt=json")
>>> eval(a.read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 7, in <module>
NameError: name 'true' is not defined
-- b'{\n  "responseHeader":{\n    "status":0,\n    "QTime":0,\n    "params":{\n      "q":"*",\n      "wt":"json"}},\n  "response":{"numFound":0,"start":0,"numFoundExact":true,"docs":[]\n  }}\n'
```

Catalog does not [`set -e`](https://github.com/GSA/catalog.data.gov/blob/main/ckan/setup/ckan_setup.sh#L1-L11) on startup.
Inventory used to [`set -e`](https://github.com/GSA/inventory-app/blob/main/start.sh#L1-L5).  

I took out the hard kill to get tests to actually run with the new error.  The real fix requires an upstream fix to `prerun.py`.

**Comment by nickumia-reisys** [comment]
Currently, the tests are failing because users can't login.  I don't know how this is affected by the Solr 8 integration.  But I suspect that once that login issue is solved, the tests will pass normally again

https://user-images.githubusercontent.com/85196563/147796900-89aca37d-f489-40e5-9121-a39efefd4822.mp4

ckan_login
.

**Comment by nickumia-reisys** [comment]
This PR is very much tied to https://github.com/GSA/catalog.data.gov/pull/392

**Comment by jbrown-xentity** [comment]
Here's the trick: this IS tied to SOLR changes. OKFN image does some setup for us, we invoke it [here](https://github.com/GSA/inventory-app/blob/main/start.sh#L70). [This prerun.py script](https://github.com/okfn/docker-ckan/blob/master/ckan-base/2.9/setup/prerun.py) runs the user setup last. I was able to catch the failure happening, it occurs in the SOLR verification step in the [prerun.py script](https://github.com/okfn/docker-ckan/blob/master/ckan-base/2.9/setup/prerun.py#L85). We need to debug if this is catching a misconfiguration/failure, or if it's using solrv6 api and we just need to update/override okfn prerun.py...
Here's the log, in case it's useful (not very), starts at "datastore initialization" and shows that it skips user stuff and goes straight to the extension setup (skips the rest of the prerun.py):
```
ckan_1                  | [prerun] Initializing datastore db - start
ckan_1                  | [prerun] Initializing datastore db - end
ckan_1                  | b''
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "prerun.py", line 203, in <module>
ckan_1                  |     check_solr_connection()
ckan_1                  |   File "prerun.py", line 85, in check_solr_connection
ckan_1                  |     eval(connection.read())
ckan_1                  |   File "<string>", line 8, in <module>
ckan_1                  | NameError: name 'true' is not defined
ckan_1                  | /app/ckan/setup/ckan_setup.sh: Running init file /docker-entrypoint.d/10-setup-harvest.sh
```

**Comment by nickumia-reisys** [comment]
To justify the last commit, this was the Peak RAM usage, 

image

**Comment by nickumia-reisys** [comment]
Need to pin the following requirements because of CKAN:
- [Jinja2<=2.11.3](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2)
- [MarkupSafe<2.1.0](https://github.com/aws/aws-sam-cli/issues/3661)

This causes Snyk to fail 💢

**Comment by nickumia-reisys** [comment]
I don't see a clear way of fixing Snyk.  @GSA/data-gov-team 👓?

**Comment by jbrown-xentity** [comment]
@nickumia-reisys see latest push; can't have dev requirements that are main requirements (they step on each other)...

**Review by FuhuXia — APPROVED** [review]

**Review by Tylorjohnson40 — APPROVED** [review]

**Pull request merged**
