### PR TITLE
[Snyk + GH Actions] Update requirements

### PR DESCRIPTION
**Pull request by Jin-Sun-tts**
Update requirements
- Updated `requirements.in` + `requirements.txt`
- Auto-generated by [snyk.yml][1]

[1]: https://github.com/gsa/inventory-app/.github/workflows/snyk.yml

### CODE REVIEW

**Review by jbrown-xentity — DISMISSED** [review]
I think the snyk rejection is bad; we're beyond the recommended patch version and the vulnerability is non-existent. If we need to move past this one, we can make an exception in the .snyk file and move on.

**Comment by btylerburton** [comment]
what's the status on this?

**Comment by btylerburton** [comment]
Related to: https://github.com/GSA/data.gov/issues/4571

**Comment by btylerburton** [comment]
Closing this as I believe now the next SNYK scan shouldn't try to update CKAN.

**Pull request closed without merging**
