### PR TITLE
[Snyk + GH Actions] Update requirements

### PR DESCRIPTION
**Pull request by Jin-Sun-tts**
Update requirements
- Updated `requirements.in` + `requirements.txt`
- Auto-generated by [snyk.yml][1]

[1]: https://github.com/gsa/inventory-app/.github/workflows/snyk.yml

### CODE REVIEW

**Comment by jbrown-xentity** [comment]
This only changes the requirements.in, and doesn't match requirements.txt. Current PR will only bring them out of sync... Does this need work (and should it be put in draft), or should it be closed?

**Comment by btylerburton** [comment]
I think this is blocked by this issue here: https://github.com/GSA/data.gov/issues/4217
Similar to catalog: https://github.com/GSA/catalog.data.gov/pull/1191/files

**Comment by FuhuXia** [comment]
tracked here https://github.com/GSA/inventory-app/pull/622

**Comment by btylerburton** [comment]
@FuhuXia do we need to add an exception to `.snyk` so this doesn't get automatically reopened on next scan?

**Pull request closed without merging**
