### PR TITLE
[Snyk + GH Actions] Update requirements

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Update requirements
- Updated `requirements.in` + `requirements.txt`
- Auto-generated by [snyk.yml][1]

[1]: https://github.com/gsa/inventory-app/.github/workflows/snyk.yml

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
Will be recreated properly shortly.  No need to close.  Re-running the action will update this PR.

**Review by btylerburton — APPROVED** [review]

**Review by btylerburton — DISMISSED** [review]

**Comment by jbrown-xentity** [comment]
I'm guessing that one of the upgrades is causing the "silent fail": the inventory app fails to come up at all, so the cypress tests just wait forever. I don't know if there's a better way to handle that (we want the test command to complete with a success or failure, so that the github action succeeds or fails appropriately)... the problem is the app startup has no end, so there isn't a way to "complete" that action and step into the cypress tests.
Best way to investigate is build and test locally with `make up`, and you should get a stack trace pointing to which library upgrade may be the problem...

**Comment by nickumia-reisys** [comment]
Yeah... it's a pain which is why I was avoiding it, but I'll do it soon @jbrown-xentity @btylerburton

**Comment by nickumia-reisys** [comment]
`ckanext-xloader` added a new requirement `tabulator` 😕 (it should be fixed now, unless there are more breaking changes haha..)

**Comment by jbrown-xentity** [comment]
One of the UI tests is failing... See 2 screenshots. The first is from the test, showing a typical CKAN interface. The second shows live inventory.data.gov, with customized metadata fields... Something is pretty wrong here.
image
image

**Comment by nickumia-reisys** [comment]
There seems to have been something in `ckanext-usmetadata` that broke... likely a result of this... will investigate tomorrow
- https://github.com/GSA/ckanext-usmetadata/pull/64

**Review by FuhuXia — APPROVED** [review]

**Pull request merged**
