### PR TITLE
Use the right version to avoid setup errors

### PR DESCRIPTION
**Pull request by avdata99**
Fixes https://github.com/GSA/ckanext-datajson/issues/52

### CODE REVIEW

**Comment by adborden** [comment]
It seems that we need to reconcile the `master` branch with `datagov` to resolve https://github.com/GSA/ckanext-datajson/issues/52

**Comment by avdata99** [comment]
> This change removes the data.json buttons from the organization page.
> 
> Screenshot from 2020-01-17 13-10-21

Those buttons [are showed](https://github.com/GSA/ckanext-datajson/blob/datagov/ckanext/datajson/templates/organization/read.html#L6:L6) if the _ckanext.datajson.inventory_links_enabled_ [config is True](https://github.com/GSA/ckanext-datajson/blob/datagov/ckanext/datajson/plugin.py#L47:L47). Maybe @adborden you just need to check if the config has changed.

**Comment by adborden** [comment]
Thanks @avdata99 would you include that config change in your PR?

**Comment by avdata99** [comment]
> Thanks @avdata99 would you include that config change in your PR?

I just added.

**Comment by adborden** [comment]
This works, but I think we'll wait until we merge the `datagov` branch into `master` and resolve it that way.

**Pull request closed without merging**
