### PR TITLE
Use psycopg2==2.8.4 in bionic

### PR DESCRIPTION
**Pull request by FuhuXia**
fixed issue https://github.com/GSA/datagov-deploy/issues/1375 and workaround for https://github.com/GSA/datagov-deploy/issues/961

### CODE REVIEW

**Comment by mogul** [comment]
The change looks fine but the test is failing:
```
Creating project_test_1 ... done
Attaching to project_test_1
test_1       | 1..4
test_1       | not ok 1 app container is up
test_1       | # (from function `wait_for' in file tests/test.bats, line 13,
test_1       | #  in test file tests/test.bats, line 35)
test_1       | #   `wait_for app 5000' failed
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | # nc: bad address 'app'
test_1       | not ok 2 /user/login is up
test_1       | # (in test file tests/test.bats, line 39)
test_1       | #   `curl --silent --fail http://app:5000/user/login' failed with status 6
test_1       | not ok 3 data is accessible for user
test_1       | # (from function `test_login_and_datasets' in file tests/test.bats, line 23,
test_1       | #  in test file tests/test.bats, line 43)
test_1       | #   `test_login_and_datasets' failed with status 6
test_1       | not ok 4 data is inaccessible to public
test_1       | # (in test file tests/test.bats, line 49)
test_1       | #   `[ "$status" -eq 22 ]' failed with status 6
project_test_1 exited with code 1
Aborting on container exit...
make: *** [test] Error 1

Exited with code exit status 2
```

**Comment by jbrown-xentity** [comment]
Something is now causing inventory to break every time, same error. Doesn't matter what branch I'm using, they have all started breaking. It must be occurring because of something external, otherwise why would every branch be failing? See thread in datagov-ckan-multi in slack...

**Comment by adborden** [comment]
Hey folks, I thought 2.8.4 was causing https://github.com/GSA/datagov-deploy/issues/961. Why are we trying to update it?

**Comment by FuhuXia** [comment]
@adborden because 2.7.7 creates a more critical issue https://github.com/GSA/datagov-deploy/issues/1375. we can use 2.8.4 as along as we skip database tag. if we need run db init command, we have to temporally use 2.7.7 then switch back to 2.8.4 afterwards. that is the workaround I found.

**Comment by adborden** [comment]
Nm, I see the work around for https://github.com/GSA/datagov-deploy/issues/961 is what caused https://github.com/GSA/datagov-deploy/issues/1375. Unfortunately, that means without the work around, we can't initialize the db for the automated tests.

**Pull request merged**
