### PR TITLE
Add production to staging

### PR DESCRIPTION
**Pull request by jbrown-xentity**
Related to https://github.com/GSA/data.gov/issues/3880

Missed production, but all tests look good. Can manually run the cf command, and staging command ran (just didn't work initially).

### CODE REVIEW

**Review by nickumia-reisys — DISMISSED** [review]
You realize the automatic version of this didn't work, right?  Manually running it works, but it doesn't do anything because it never detected a change in the files,

Automatic (fail): https://github.com/GSA/inventory-app/runs/7241422816?check_suite_focus=true
image

Manual (success, but not verified): https://github.com/GSA/inventory-app/runs/7241438151?check_suite_focus=true
image

**Comment by jbrown-xentity** [comment]
> You realize the automatic version of this didn't work, right? Manually running it works, but it doesn't do anything because it never detected a change in the files,
> 

Good catch @nickumia-reisys! I missed something, this last commit should fix it.

**Review by nickumia-reisys — APPROVED** [review]
Interesting fix, we'll see 👁️‍🗨️

**Comment by nickumia-reisys** [comment]
Nope... still didn't work 😞 

image

**Comment by nickumia-reisys** [comment]
Scratch that... maybe there wasn't a change this time haha... oh well.

**Comment by jbrown-xentity** [comment]
There wasn't a change. This is a great optimization if it works, but it's hard to test (requires a push to main in current form).
Now that it is deployed, I might try a branch where I remove the push to main part and see if I can check if the file has changed and get it to fire...

**Pull request merged**
