### PR TITLE
Create issue on deployment failure

### PR DESCRIPTION
**Pull request by jbrown-xentity**
[Working Example](https://github.com/GSA/datagov-deploy/issues/2799). Uses the [github-script action](https://github.com/actions/github-script). Related to https://github.com/GSA/datagov-deploy/issues/2603.

This step should be attachable to any github actions job, and should work (inside the GSA org; need a special permission token to create issues and comment on them; see [here](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) for more details).

Would like to harden this before deploying, because if this code is going to be copied and utilized in different repositories for action workflows we do not want to be updating it in 10 different repo's...

Anyone that has a workflow that fails gets an email (I got many while testing this code), so even if this task fails an email will go out to the specific user who merged the commit to main/develop.

Things to consider:
- Can we re-use a task, so we only define this once per action (could not find any documentation one way or another)?
- Should we use [Object.assign or the Spread Operator](https://attacomsian.com/blog/javascript-merge-objects)?
- Should we use any try-catch blocks?

### CODE REVIEW

**Review by adborden — DISMISSED** [review]
Looks good! This is too much code to copy/paste so we're going to want to move this to a proper action.

**Comment by jbrown-xentity** [comment]
> Looks good! This is too much code to copy/paste so we're going to want to move this to a proper action.

I see the [github-script](https://github.com/actions/github-script#run-a-separate-file) library lets you run a file... Do we want to write a script and attach to each repo? Do we want to make a new repo and pull that into the action? Or do we need to make a full action with variable input and publish it to the marketplace?

**Comment by adborden** [comment]
> I see the [github-script](https://github.com/actions/github-script#run-a-separate-file) library lets you run a file... Do we want to write a script and attach to each repo? Do we want to make a new repo and pull that into the action? Or do we need to make a full action with variable input and publish it to the marketplace?

It should be a full action with variable input and published to the marketplace.

**Comment by jbrown-xentity** [comment]
Closing in place of writing a ticket... https://github.com/GSA/datagov-deploy/issues/2827

**Pull request closed without merging**
