### PR TITLE
bump localstack version in docker-compose to 1.3.1

### PR DESCRIPTION
**Pull request by robert-bryson**
The current version of `localstack` we're using (`0.11.0`) is a [couple of years old](https://github.com/localstack/localstack/releases/tag/v0.11.0). Current latest is [`1.0.4`](https://github.com/localstack/localstack/releases/tag/v1.0.4). Happened to notice this when setting up `localstack` for another ticket.

### CODE REVIEW

**Review by btylerburton — DISMISSED** [review]
Upgrade!

**Comment by btylerburton** [comment]
tests seem to be hanging

**Comment by robert-bryson** [comment]
> tests seem to be hanging

Sure does. [Rerunning](https://github.com/GSA/inventory-app/actions/runs/4000672021).

**Comment by nickumia-reisys** [comment]
Fixing this issue now,

```bash
localstack-container    | ERROR
localstack-container    | ============================================================================
localstack-container    |   It seems you are mounting the LocalStack volume into /tmp/localstack.
localstack-container    |   This will break the LocalStack container! Please update your volume mount
localstack-container    |   destination to /var/lib/localstack.
localstack-container    |   You can suppress this error by setting LEGACY_DIRECTORIES=1.
localstack-container    |
localstack-container    |   See: https://github.com/localstack/localstack/issues/6398
localstack-container    | ============================================================================
localstack-container    |
localstack-container    | ERROR
localstack-container    | ============================================================================
localstack-container    |   It seems you are mounting the LocalStack volume into /tmp/localstack.
localstack-container    |   This will break the LocalStack container! Please update your volume mount
localstack-container    |   destination to /var/lib/localstack.
localstack-container    |   You can suppress this error by setting LEGACY_DIRECTORIES=1.
localstack-container    |
localstack-container    |   See: https://github.com/localstack/localstack/issues/6398
localstack-container    | ============================================================================
localstack-container    |
localstack-container exited with code 1
```

**Comment by nickumia-reisys** [comment]
Pending fix from
- https://github.com/GSA/inventory-app/pull/542

**Review by nickumia-reisys — APPROVED** [review]
🤙

**Pull request merged**
