### PR TITLE
moved to datagov

### PR DESCRIPTION
**Pull request by robert-bryson**
Related to https://github.com/GSA/data.gov/issues/4193

With https://github.com/GSA/data.gov/pull/4198, these are now in [datagov](https://github.com/GSA/data.gov/tree/main/.github).

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
I added it to the open PR (which isn't passing tests and I'm not sure why)
- https://github.com/GSA/inventory-app/pull/541

**Comment by nickumia-reisys** [comment]
Tests most likely hanging with,
```bash
ckan_1                  |   File "/usr/bin/ckan", line 8, in <module>
ckan_1                  |     sys.exit(ckan())
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
ckan_1                  |     return self.main(*args, **kwargs)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1054, in main
ckan_1                  |     with self.make_context(prog_name, args, **extra) as ctx:
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 920, in make_context
ckan_1                  |     self.parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 115, in parse_args
ckan_1                  |     result = super(ExtendableGroup, self).parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
ckan_1                  |     rest = super().parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
ckan_1                  |     value, args = param.handle_parse_result(ctx, opts, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
ckan_1                  |     value = self.process_value(ctx, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
ckan_1                  |     value = self.callback(ctx, self, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 125, in _init_ckan_config
ckan_1                  |     _add_ctx_object(ctx, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 134, in _add_ctx_object
ckan_1                  |     ctx.obj = CtxObject(path)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 56, in __init__
ckan_1                  |     self.app = make_app(self.config)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/middleware/__init__.py", line 58, in make_app
ckan_1                  |     flask_app = make_flask_stack(conf)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/middleware/flask_app.py", line 168, in make_flask_stack
ckan_1                  |     raise RuntimeError(u'You must provide a value for the secret key'
ckan_1                  | RuntimeError: You must provide a value for the secret key with the SECRET_KEY config option
inventory-app_ckan_1 exited with code 1
```

Trying to get it working again.

**Review by btylerburton — APPROVED** [review]

**Comment by nickumia-reisys** [comment]
I found a fix!  It's incoming 😎

**Comment by nickumia-reisys** [comment]
Updated status,  the tests are running, but login is currently broken (at least for the tests).  Locally, if you login the first time, it fails with 403 and then waiting a bit (minimum 10-15 secs), attempting to login again succeeds.. I don't have any clue what's going on, but it's strange. @jbrown-xentity @FuhuXia @btylerburton @robert-bryson @Jin-Sun-tts

**Comment by nickumia-reisys** [comment]
Sooo (in summary 🙄), the problem was the following commit in the upstream `ofkn/docker-ckan` image,
- https://github.com/okfn/docker-ckan/commit/4746d8cc9d1a6ecb0c209cdf501b8d0f4f3cd224#diff-873767dcc2aa67a037308b99266c75f5603de69431190f82400cdbb82055fdd9

We needed to incorporate both of the changes in that commit to get this to pass 🗞️

**Review by nickumia-reisys — APPROVED** [review]
➿

**Pull request merged**
